language: python

python:
  - "3.6"

install:
  - pip install mkdocs
  - echo -e "machine github.com\n  login ${GITHUB_TOKEN}" > ~/.netrc
  - pip install mkdocs-material

script:
  - mkdocs gh-deploy --force --clean
  - git checkout gh-pages
  - git pull
  - echo "apple-docs.echosun.xyz" > CNAME
  - git add CNAME
  - git commit -m "Change CNAME"
  - git push
branches:
  only:
    - master
